# Site settings
title: Pamela Bortnick's Blog
header-img: img/home-bg.png
email: pbortnick@gmail.com
copyright_name: pbortnick
description: > # this means to ignore newlines until "baseurl:"
  PHB
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  pbortnick
learn_profile: pbortnick
email_username: pbortnick@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
